name: CI

on:
  push:
    branches: [main,test-e2e,test-deploy]
  pull_request:
    branches: [main,test-e2e,test-deploy]
  workflow_dispatch:

########################
# 1) BUILD
########################
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build # crea .next en la raíz

      # (Opcional) comprueba que .next existe
      - run: ls -a . | grep '\.next'

      - name: Upload .next artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build # ← este nombre se usará al descargar
          path: .next # ← ruta correcta
          retention-days: 1

  ########################
  # 2) UNIT TESTS (Jest)
  ########################
  unit:
    needs: build
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run test:unit

  ########################
  # 3) E2E TESTS (Playwright)
  ########################
  e2e:
    needs: [build, unit] # sólo corre si build y unit = success
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build # ← mismo nombre
          path: .next # ← destino donde lo usará `next start`

      - run: npx playwright install --with-deps

      - run: npm run test:e2e # script que ejecuta Playwright

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
