name: CI

on:
  push:
    branches: [main, test-e2e]
  pull_request:
    branches: [main, test-e2e]
  workflow_dispatch:

########################
# 1) BUILD
########################
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Upload .next artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next/** # incluye todo el contenido
          retention-days: 1

  ########################
  # 2) TESTS (unit + e2e en paralelo)
  ########################
  tests:
    needs: build # se lanza cuando build = success
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: true # ← si un eje falla, cancela el otro
      matrix:
        kind: [unit, e2e] # dos “sub-jobs” paralelos

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci

      # ────────── UNIT ──────────
      - name: Run unit tests
        if: ${{ matrix.kind == 'unit' }}
        run: npm run test:unit

      # ────────── E2E ──────────
      - name: Prepare E2E build
        if: ${{ matrix.kind == 'e2e' }}
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .next # restaura la build

      - name: Install Playwright browsers
        if: ${{ matrix.kind == 'e2e' }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ matrix.kind == 'e2e' }}
        run: npm run test:e2e

      - name: Upload Playwright report
        if: ${{ matrix.kind == 'e2e' && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
