# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main] # ajusta a tus ramas
  pull_request:
    branches: [main]
  workflow_dispatch: # ejecución manual opcional

# ────────────────────────────
# 1) Tests unitarios (Jest)
# ────────────────────────────
jobs:
  unit:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm # cache de ~/.npm entre ejecuciones

      - run: npm ci

      - name: Run unit tests
        run: npm run test:unit # ← script que dispara Jest

  # ────────────────────────────
  # 2) Tests E2E (Playwright)
  # ────────────────────────────
  e2e:
    needs: unit # ← depende de que 'unit' termine OK
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build Next.js App
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
