name: CI

on:
  push:
    branches: [main, test-e2e]
  pull_request:
    branches: [main, test-e2e]
  workflow_dispatch:

jobs:
  #────────── 1) MATRIX: unit | e2e ──────────#
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      matrix:
        kind: [unit, e2e] # dos jobs paralelos
      fail-fast: true # ⬅️  si uno falla, cancela el otro

    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      # 0) Código + Node
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci

      # 1) Build de Next (lo hace cada job)
      - name: Build Next.js
        run: npm run build

      # 2) UNIT ───────────────
      - name: Run unit tests
        if: ${{ matrix.kind == 'unit' }}
        run: npm run test:unit

      # 3) E2E ────────────────
      - name: Install Playwright browsers
        if: ${{ matrix.kind == 'e2e' }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ matrix.kind == 'e2e' }}
        run: npm run test:e2e

      - name: Upload Playwright report
        if: ${{ matrix.kind == 'e2e' && !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
